Repository meateam/api-gateway, pull requests merged in 2019-06, with the labels that each got.

#37 Develop
  .gitignore
  .golangci.yml
  .vscode/launch.json
  Dockerfile
  Makefile
  docker-compose.yml
  file.go
  go.mod
  go.sum
  logger/logger.go
  main.go
  router.go
  upload.go
Labels: enhancement

#42 Feature/logs
  go.mod
  go.sum
  logger/logger.go
  upload.go
Labels: bug

#43 Develop - update elasticsearch-logger
  go.mod
  go.sum
  logger/logger.go
  upload.go
Labels: bug

#44 map grpc status code to http from file-service responses
  file.go
  upload.go
Labels: bug

#45 Develop - map file-service grpc status code to http and fix logger SkipBodyPathRegexp
  docker-compose.yml
  file.go
  logger/logger.go
  upload.go
Labels: bug, enhancement

#46 Feature/auth
  auth.go
  docker-compose.yml
  go.mod
  go.sum
  main.go
  router.go
  user.go
Labels: enhancement

#47 Develop - auth
  auth.go
  docker-compose.yml
  go.mod
  go.sum
  main.go
  router.go
  user.go
Labels: enhancement

#52 add configuration for apm in UI
  docker-compose.yml
  main.go
  router.go
Labels: bug, enhancement

#53 Develop
  docker-compose.yml
  main.go
  router.go
Labels: bug, enhancement

#51 Hotfix/update upload
  .vscode/launch.json
  docker-compose.yml
  file.go
  go.mod
  go.sum
  logger/logger.go
  upload.go
Labels: bug

#55 Hotfix/quota
  go.mod
  go.sum
  logger/logger.go
  router.go
  upload.go
Labels: bug, enhancement

#54 Develop
  .vscode/launch.json
  docker-compose.yml
  file.go
  go.mod
  go.sum
  logger/logger.go
  router.go
  upload.go
Labels: bug, enhancement

#56 update elasticsearch-logger to v1.1.2
  go.mod
  go.sum
Labels: enhancement

#58 Hotfix/healthcheck ignore
  router.go
Labels: bug, enhancement

#59 Develop
  router.go
Labels: bug, enhancement

#60 changed auth redirect from being permanent to being temporary
  auth.go
Labels: bug

#61 disable apm capture body and handle EOF error from stream.Send
  .vscode/launch.json
  upload.go
Labels: bug, enhancement
